/*
 * File: app/view/landingPage.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('StripeCheckoutSample.view.landingPage', {
    extend: 'Ext.Container',
    alias: 'widget.landingpage',

    requires: [
        'Ext.Label',
        'Ext.Button',
        'Ext.form.Panel',
        'Ext.field.Number'
    ],

    config: {
        itemId: 'landingPage',
        items: [
            {
                xtype: 'container',
                itemId: 'headlineContainer',
                margin: '10% 0 0 0',
                items: [
                    {
                        xtype: 'label',
                        html: '<center><span style="font-size:24px; font-weight:bold;">Stripe Checkout Sample</span></center>',
                        itemId: 'headline'
                    }
                ]
            },
            {
                xtype: 'container',
                html: 'The purpose of this application is to simply test the functionality of Stripe Checkout. <br><br> To get started, click on "Generate item" to create a sample product to transact with.',
                itemId: 'instructionContainer',
                margin: '10% 0 0 0'
            },
            {
                xtype: 'container',
                itemId: 'itemGeneratorContainer',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'generateItemButton',
                        margin: '10% 0 0 0 ',
                        text: 'Generate Item'
                    },
                    {
                        xtype: 'formpanel',
                        height: 200,
                        itemId: 'itemDetails',
                        items: [
                            {
                                xtype: 'numberfield',
                                itemId: 'priceField',
                                label: 'Price (in cents)',
                                labelWidth: '50%'
                            },
                            {
                                xtype: 'textfield',
                                itemId: 'merchantField',
                                label: 'Merchant',
                                labelWidth: '50%'
                            },
                            {
                                xtype: 'textfield',
                                itemId: 'descriptionField',
                                label: 'Description',
                                labelWidth: '50%'
                            },
                            {
                                xtype: 'button',
                                itemId: 'buyItemButton',
                                text: 'Buy Now'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});